import type { PrimitiveId } from '@opsis/schema';
import { BOX_ANCHORS, COMPASS_ANCHORS } from './anchors';
import type { PrimitiveMeta, Vec3 } from './meta';

const BOTH: PrimitiveMeta['dimensions'] = ['2d', '3d'];
const UP: Vec3 = [0, 1, 0];

/**
 * Render-free metadata for every primitive (PROMPT.md §9): ids, keywords, anchors. Pure data with
 * no React import, so pipeline stages can match entities to primitives on the server.
 * Order is the tie-break order for matching.
 */
export const PRIMITIVE_CATALOG: readonly PrimitiveMeta[] = [
  // Direction
  {
    id: 'compass',
    category: 'direction',
    keywords: [
      'compass',
      'direction',
      'bearing',
      'north',
      'south',
      'east',
      'west',
      'northeast',
      'northwest',
      'southeast',
      'southwest',
      'cardinal',
    ],
    dimensions: BOTH,
    colorToken: 'direction.dial',
    anchors: COMPASS_ANCHORS,
    anchorLabels: { N: 'N', E: 'E', S: 'S', W: 'W' },
    summary: 'A compass shows the directions north, east, south and west.',
  },
  {
    id: 'arrow',
    category: 'direction',
    keywords: ['arrow', 'pointer', 'move', 'go', 'push', 'pull', 'toward', 'force', 'vector'],
    dimensions: BOTH,
    colorToken: 'flow.arrow',
    anchors: { ...BOX_ANCHORS, tail: [-0.5, 0, 0], head: [0.5, 0, 0] },
  },
  {
    id: 'curved_arrow',
    category: 'direction',
    keywords: [
      'rise',
      'rising',
      'set',
      'setting',
      'curve',
      'arc',
      'orbit',
      'turn',
      'rotate',
      'spin',
      'climb',
      'ascend',
    ],
    dimensions: BOTH,
    colorToken: 'flow.arrow',
    anchors: { ...BOX_ANCHORS, tail: [-0.4, -0.4, 0], head: [0.3, 0.25, 0] },
  },
  {
    id: 'horizon',
    category: 'direction',
    keywords: ['horizon', 'ground', 'land', 'skyline', 'surface', 'sky'],
    dimensions: BOTH,
    colorToken: 'nature.ground',
    summary: 'The horizon is where the land seems to meet the sky.',
    anchors: BOX_ANCHORS,
  },
  // Celestial
  {
    id: 'sun',
    category: 'celestial',
    keywords: ['sun', 'star', 'sunlight', 'sunshine', 'daylight', 'solar'],
    dimensions: BOTH,
    colorToken: 'celestial.sun',
    anchors: BOX_ANCHORS,
  },
  {
    id: 'moon',
    category: 'celestial',
    keywords: ['moon', 'lunar', 'satellite', 'crescent'],
    dimensions: BOTH,
    colorToken: 'celestial.moon',
    anchors: BOX_ANCHORS,
  },
  {
    id: 'earth',
    category: 'celestial',
    keywords: ['earth', 'planet', 'world', 'globe'],
    dimensions: BOTH,
    colorToken: 'celestial.earth',
    anchors: BOX_ANCHORS,
  },
  // Nature
  {
    id: 'cloud',
    category: 'nature',
    keywords: ['cloud', 'fog', 'mist', 'vapour', 'vapor', 'condensation', 'steam'],
    dimensions: BOTH,
    colorToken: 'nature.cloud',
    anchors: BOX_ANCHORS,
  },
  {
    id: 'raindrop',
    category: 'nature',
    keywords: ['rain', 'raindrop', 'drop', 'droplet', 'precipitation', 'tear', 'drip'],
    dimensions: BOTH,
    colorToken: 'nature.water',
    anchors: BOX_ANCHORS,
  },
  {
    id: 'tree',
    category: 'nature',
    keywords: ['tree', 'forest', 'plant', 'pine', 'oak', 'wood'],
    dimensions: BOTH,
    colorToken: 'nature.leaf',
    anchors: BOX_ANCHORS,
  },
  {
    id: 'leaf',
    category: 'nature',
    keywords: ['leaf', 'foliage', 'lettuce', 'chlorophyll', 'photosynthesis', 'herb'],
    dimensions: BOTH,
    colorToken: 'nature.leaf',
    anchors: BOX_ANCHORS,
  },
  {
    id: 'water',
    category: 'nature',
    keywords: ['water', 'ocean', 'sea', 'lake', 'river', 'pond', 'liquid'],
    dimensions: BOTH,
    colorToken: 'nature.water',
    anchors: BOX_ANCHORS,
  },
  {
    id: 'mountain',
    category: 'nature',
    keywords: ['mountain', 'hill', 'peak', 'volcano', 'summit'],
    dimensions: BOTH,
    colorToken: 'nature.rock',
    anchors: BOX_ANCHORS,
  },
  // Containers / structure
  {
    id: 'box',
    category: 'container',
    keywords: ['box', 'container', 'crate', 'package', 'chest', 'cube'],
    dimensions: BOTH,
    colorToken: 'struct.container',
    anchors: BOX_ANCHORS,
  },
  {
    id: 'stack_layer',
    category: 'container',
    keywords: [
      'layer',
      'stratum',
      'strata',
      'level',
      'tier',
      'crust',
      'mantle',
      'core',
      'atmosphere',
    ],
    dimensions: BOTH,
    colorToken: 'struct.layer',
    anchors: BOX_ANCHORS,
    explodeAxis: UP,
  },
  {
    id: 'bowl',
    category: 'container',
    keywords: ['bowl', 'dish', 'cup', 'basin', 'pot'],
    dimensions: ['3d'],
    colorToken: 'struct.container',
    anchors: BOX_ANCHORS,
  },
  {
    id: 'cell',
    category: 'container',
    keywords: ['cell', 'membrane', 'nucleus', 'bacterium', 'organism', 'atom'],
    dimensions: ['3d'],
    colorToken: 'struct.container',
    anchors: BOX_ANCHORS,
  },
  {
    id: 'group_frame',
    category: 'container',
    keywords: ['group', 'set', 'collection', 'whole', 'system', 'frame'],
    dimensions: BOTH,
    colorToken: 'struct.frame',
    summary: 'This frame groups the parts that make up the whole.',
    anchors: BOX_ANCHORS,
  },
  // Food
  {
    id: 'bread_slice',
    category: 'food',
    keywords: ['bread', 'toast', 'bun', 'loaf', 'baguette'],
    dimensions: BOTH,
    colorToken: 'food.bread',
    anchors: BOX_ANCHORS,
    explodeAxis: UP,
  },
  {
    id: 'generic_layer',
    category: 'food',
    keywords: [
      'ham',
      'cheese',
      'meat',
      'bacon',
      'filling',
      'patty',
      'egg',
      'butter',
      'spread',
      'sauce',
    ],
    dimensions: BOTH,
    colorToken: 'food.generic',
    anchors: BOX_ANCHORS,
    explodeAxis: UP,
  },
  {
    id: 'round_fruit',
    category: 'food',
    keywords: [
      'fruit',
      'tomato',
      'apple',
      'orange',
      'peach',
      'plum',
      'berry',
      'cherry',
      'vegetable',
    ],
    dimensions: BOTH,
    colorToken: 'food.fruit',
    anchors: BOX_ANCHORS,
  },
  {
    id: 'slice',
    category: 'food',
    keywords: ['slice', 'section', 'cucumber', 'wedge', 'piece'],
    dimensions: BOTH,
    colorToken: 'food.tomato',
    anchors: BOX_ANCHORS,
    explodeAxis: UP,
  },
  // People
  {
    id: 'person',
    category: 'people',
    keywords: [
      'person',
      'people',
      'human',
      'man',
      'woman',
      'child',
      'student',
      'teacher',
      'farmer',
      'worker',
      'someone',
    ],
    dimensions: BOTH,
    colorToken: 'people.cloth',
    anchors: { ...BOX_ANCHORS, head: [0, 0.4, 0], hand: [0.25, -0.05, 0] },
  },
  {
    id: 'hand',
    category: 'people',
    keywords: ['hand', 'finger', 'palm', 'grab', 'hold', 'touch'],
    dimensions: ['3d'],
    colorToken: 'people.skin',
    anchors: BOX_ANCHORS,
  },
  // Flow / measure
  {
    id: 'cycle_ring',
    category: 'flow',
    keywords: ['cycle', 'loop', 'circle', 'repeat', 'recycle', 'circulation'],
    dimensions: BOTH,
    colorToken: 'flow.ring',
    anchors: {
      ...BOX_ANCHORS,
      '12': [0, 0.4, 0],
      '3': [0.4, 0, 0],
      '6': [0, -0.4, 0],
      '9': [-0.4, 0, 0],
    },
  },
  {
    id: 'timeline_axis',
    category: 'flow',
    keywords: ['timeline', 'time', 'history', 'sequence', 'era', 'before', 'after', 'step'],
    dimensions: BOTH,
    colorToken: 'flow.arrow',
    anchors: { ...BOX_ANCHORS, start: [-0.5, 0, 0], end: [0.5, 0, 0] },
  },
  {
    id: 'scale_balance',
    category: 'measure',
    keywords: [
      'scale',
      'balance',
      'compare',
      'weigh',
      'weight',
      'heavier',
      'lighter',
      'bigger',
      'smaller',
    ],
    dimensions: ['3d'],
    colorToken: 'measure.metal',
    anchors: { ...BOX_ANCHORS, left_pan: [-0.4, 0.05, 0], right_pan: [0.4, 0.05, 0] },
  },
  {
    id: 'bar',
    category: 'measure',
    keywords: ['bar', 'amount', 'height', 'level', 'quantity', 'chart', 'measure'],
    dimensions: BOTH,
    colorToken: 'measure.bar',
    anchors: BOX_ANCHORS,
  },
  {
    id: 'counter_dots',
    category: 'measure',
    keywords: ['count', 'number', 'dots', 'many', 'few', 'several', 'dozen'],
    dimensions: BOTH,
    colorToken: 'ui.accent',
    anchors: BOX_ANCHORS,
  },
  // Fallback
  {
    id: 'labeled_card',
    category: 'generic',
    keywords: ['card', 'label', 'note', 'thing', 'concept'],
    dimensions: BOTH,
    colorToken: 'ui.card',
    anchors: BOX_ANCHORS,
  },
];

/** The primitive that always renders. */
export const FALLBACK_PRIMITIVE_ID: PrimitiveId = 'labeled_card';

/** Every primitive id in the catalog, in tie-break order. */
export const PRIMITIVE_IDS: readonly PrimitiveId[] = PRIMITIVE_CATALOG.map((meta) => meta.id);

/** True when `id` names a registered primitive (used to validate LLM suggestions). */
export function isPrimitiveId(id: string): id is PrimitiveId {
  return (PRIMITIVE_IDS as readonly string[]).includes(id);
}
