import type { PrimitiveId } from '@opsis/schema';
import { BOX_ANCHORS, COMPASS_ANCHORS } from './anchors';
import * as R2 from './render2d';
import { Arrow, Compass, CurvedArrow, Horizon } from './render3d/direction';
import { LabeledCard } from './render3d/fallback';
import { Bar, CounterDots, CycleRing, ScaleBalance, TimelineAxis } from './render3d/flow';
import { BreadSlice, GenericLayer, RoundFruit, Slice } from './render3d/food';
import { Cloud, Earth, Leaf, Moon, Mountain, Raindrop, Sun, Tree, Water } from './render3d/nature';
import { Hand, Person } from './render3d/people';
import { Bowl, Box, Cell, GroupFrame, StackLayer } from './render3d/structure';
import type { PrimitiveDef, Vec3 } from './types';

const BOTH: PrimitiveDef['dimensions'] = ['2d', '3d'];
const UP: Vec3 = [0, 1, 0];

/** Every primitive in the library (PROMPT.md §9). Order is the tie-break order for matching. */
export const PRIMITIVES: readonly PrimitiveDef[] = [
  // Direction
  {
    id: 'compass',
    category: 'direction',
    keywords: [
      'compass',
      'direction',
      'bearing',
      'north',
      'south',
      'east',
      'west',
      'northeast',
      'northwest',
      'southeast',
      'southwest',
      'cardinal',
    ],
    dimensions: BOTH,
    colorToken: 'direction.dial',
    render3D: Compass,
    render2D: R2.Compass2D,
    anchors: COMPASS_ANCHORS,
    anchorLabels: { N: 'N', E: 'E', S: 'S', W: 'W' },
    summary: 'A compass shows the directions north, east, south and west.',
  },
  {
    id: 'arrow',
    category: 'direction',
    keywords: ['arrow', 'pointer', 'move', 'go', 'push', 'pull', 'toward', 'force', 'vector'],
    dimensions: BOTH,
    colorToken: 'flow.arrow',
    render3D: Arrow,
    render2D: R2.Arrow2D,
    anchors: { ...BOX_ANCHORS, tail: [-0.5, 0, 0], head: [0.5, 0, 0] },
  },
  {
    id: 'curved_arrow',
    category: 'direction',
    keywords: [
      'rise',
      'rising',
      'set',
      'setting',
      'curve',
      'arc',
      'orbit',
      'turn',
      'rotate',
      'spin',
      'climb',
      'ascend',
    ],
    dimensions: BOTH,
    colorToken: 'flow.arrow',
    render3D: CurvedArrow,
    render2D: R2.CurvedArrow2D,
    anchors: { ...BOX_ANCHORS, tail: [-0.4, -0.4, 0], head: [0.3, 0.25, 0] },
  },
  {
    id: 'horizon',
    category: 'direction',
    keywords: ['horizon', 'ground', 'land', 'skyline', 'surface', 'sky'],
    dimensions: BOTH,
    colorToken: 'nature.ground',
    summary: 'The horizon is where the land seems to meet the sky.',
    render3D: Horizon,
    render2D: R2.Horizon2D,
    anchors: BOX_ANCHORS,
  },
  // Celestial
  {
    id: 'sun',
    category: 'celestial',
    keywords: ['sun', 'star', 'sunlight', 'sunshine', 'daylight', 'solar'],
    dimensions: BOTH,
    colorToken: 'celestial.sun',
    render3D: Sun,
    render2D: R2.Sun2D,
    anchors: BOX_ANCHORS,
  },
  {
    id: 'moon',
    category: 'celestial',
    keywords: ['moon', 'lunar', 'satellite', 'crescent'],
    dimensions: BOTH,
    colorToken: 'celestial.moon',
    render3D: Moon,
    render2D: R2.Moon2D,
    anchors: BOX_ANCHORS,
  },
  {
    id: 'earth',
    category: 'celestial',
    keywords: ['earth', 'planet', 'world', 'globe'],
    dimensions: BOTH,
    colorToken: 'celestial.earth',
    render3D: Earth,
    render2D: R2.Earth2D,
    anchors: BOX_ANCHORS,
  },
  // Nature
  {
    id: 'cloud',
    category: 'nature',
    keywords: ['cloud', 'fog', 'mist', 'vapour', 'vapor', 'condensation', 'steam'],
    dimensions: BOTH,
    colorToken: 'nature.cloud',
    render3D: Cloud,
    render2D: R2.Cloud2D,
    anchors: BOX_ANCHORS,
  },
  {
    id: 'raindrop',
    category: 'nature',
    keywords: ['rain', 'raindrop', 'drop', 'droplet', 'precipitation', 'tear', 'drip'],
    dimensions: BOTH,
    colorToken: 'nature.water',
    render3D: Raindrop,
    render2D: R2.Raindrop2D,
    anchors: BOX_ANCHORS,
  },
  {
    id: 'tree',
    category: 'nature',
    keywords: ['tree', 'forest', 'plant', 'pine', 'oak', 'wood'],
    dimensions: BOTH,
    colorToken: 'nature.leaf',
    render3D: Tree,
    render2D: R2.Tree2D,
    anchors: BOX_ANCHORS,
  },
  {
    id: 'leaf',
    category: 'nature',
    keywords: ['leaf', 'foliage', 'lettuce', 'chlorophyll', 'photosynthesis', 'herb'],
    dimensions: BOTH,
    colorToken: 'nature.leaf',
    render3D: Leaf,
    render2D: R2.Leaf2D,
    anchors: BOX_ANCHORS,
  },
  {
    id: 'water',
    category: 'nature',
    keywords: ['water', 'ocean', 'sea', 'lake', 'river', 'pond', 'liquid'],
    dimensions: BOTH,
    colorToken: 'nature.water',
    render3D: Water,
    render2D: R2.Water2D,
    anchors: BOX_ANCHORS,
  },
  {
    id: 'mountain',
    category: 'nature',
    keywords: ['mountain', 'hill', 'peak', 'volcano', 'summit'],
    dimensions: BOTH,
    colorToken: 'nature.rock',
    render3D: Mountain,
    render2D: R2.Mountain2D,
    anchors: BOX_ANCHORS,
  },
  // Containers / structure
  {
    id: 'box',
    category: 'container',
    keywords: ['box', 'container', 'crate', 'package', 'chest', 'cube'],
    dimensions: BOTH,
    colorToken: 'struct.container',
    render3D: Box,
    render2D: R2.Box2D,
    anchors: BOX_ANCHORS,
  },
  {
    id: 'stack_layer',
    category: 'container',
    keywords: [
      'layer',
      'stratum',
      'strata',
      'level',
      'tier',
      'crust',
      'mantle',
      'core',
      'atmosphere',
    ],
    dimensions: BOTH,
    colorToken: 'struct.layer',
    render3D: StackLayer,
    render2D: R2.Layer2D,
    anchors: BOX_ANCHORS,
    explodeAxis: UP,
  },
  {
    id: 'bowl',
    category: 'container',
    keywords: ['bowl', 'dish', 'cup', 'basin', 'pot'],
    dimensions: ['3d'],
    colorToken: 'struct.container',
    render3D: Bowl,
    anchors: BOX_ANCHORS,
  },
  {
    id: 'cell',
    category: 'container',
    keywords: ['cell', 'membrane', 'nucleus', 'bacterium', 'organism', 'atom'],
    dimensions: ['3d'],
    colorToken: 'struct.container',
    render3D: Cell,
    anchors: BOX_ANCHORS,
  },
  {
    id: 'group_frame',
    category: 'container',
    keywords: ['group', 'set', 'collection', 'whole', 'system', 'frame'],
    dimensions: BOTH,
    colorToken: 'struct.frame',
    summary: 'This frame groups the parts that make up the whole.',
    render3D: GroupFrame,
    render2D: R2.GroupFrame2D,
    anchors: BOX_ANCHORS,
  },
  // Food
  {
    id: 'bread_slice',
    category: 'food',
    keywords: ['bread', 'toast', 'bun', 'loaf', 'baguette'],
    dimensions: BOTH,
    colorToken: 'food.bread',
    render3D: BreadSlice,
    render2D: R2.BreadSlice2D,
    anchors: BOX_ANCHORS,
    explodeAxis: UP,
  },
  {
    id: 'generic_layer',
    category: 'food',
    keywords: [
      'ham',
      'cheese',
      'meat',
      'bacon',
      'filling',
      'patty',
      'egg',
      'butter',
      'spread',
      'sauce',
    ],
    dimensions: BOTH,
    colorToken: 'food.generic',
    render3D: GenericLayer,
    render2D: R2.Layer2D,
    anchors: BOX_ANCHORS,
    explodeAxis: UP,
  },
  {
    id: 'round_fruit',
    category: 'food',
    keywords: [
      'fruit',
      'tomato',
      'apple',
      'orange',
      'peach',
      'plum',
      'berry',
      'cherry',
      'vegetable',
    ],
    dimensions: BOTH,
    colorToken: 'food.fruit',
    render3D: RoundFruit,
    render2D: R2.RoundFruit2D,
    anchors: BOX_ANCHORS,
  },
  {
    id: 'slice',
    category: 'food',
    keywords: ['slice', 'section', 'cucumber', 'wedge', 'piece'],
    dimensions: BOTH,
    colorToken: 'food.tomato',
    render3D: Slice,
    render2D: R2.Slice2D,
    anchors: BOX_ANCHORS,
    explodeAxis: UP,
  },
  // People
  {
    id: 'person',
    category: 'people',
    keywords: [
      'person',
      'people',
      'human',
      'man',
      'woman',
      'child',
      'student',
      'teacher',
      'farmer',
      'worker',
      'someone',
    ],
    dimensions: BOTH,
    colorToken: 'people.cloth',
    render3D: Person,
    render2D: R2.Person2D,
    anchors: { ...BOX_ANCHORS, head: [0, 0.4, 0], hand: [0.25, -0.05, 0] },
  },
  {
    id: 'hand',
    category: 'people',
    keywords: ['hand', 'finger', 'palm', 'grab', 'hold', 'touch'],
    dimensions: ['3d'],
    colorToken: 'people.skin',
    render3D: Hand,
    anchors: BOX_ANCHORS,
  },
  // Flow / measure
  {
    id: 'cycle_ring',
    category: 'flow',
    keywords: ['cycle', 'loop', 'circle', 'repeat', 'recycle', 'circulation'],
    dimensions: BOTH,
    colorToken: 'flow.ring',
    render3D: CycleRing,
    render2D: R2.CycleRing2D,
    anchors: {
      ...BOX_ANCHORS,
      '12': [0, 0.4, 0],
      '3': [0.4, 0, 0],
      '6': [0, -0.4, 0],
      '9': [-0.4, 0, 0],
    },
  },
  {
    id: 'timeline_axis',
    category: 'flow',
    keywords: ['timeline', 'time', 'history', 'sequence', 'era', 'before', 'after', 'step'],
    dimensions: BOTH,
    colorToken: 'flow.arrow',
    render3D: TimelineAxis,
    render2D: R2.TimelineAxis2D,
    anchors: { ...BOX_ANCHORS, start: [-0.5, 0, 0], end: [0.5, 0, 0] },
  },
  {
    id: 'scale_balance',
    category: 'measure',
    keywords: [
      'scale',
      'balance',
      'compare',
      'weigh',
      'weight',
      'heavier',
      'lighter',
      'bigger',
      'smaller',
    ],
    dimensions: ['3d'],
    colorToken: 'measure.metal',
    render3D: ScaleBalance,
    anchors: { ...BOX_ANCHORS, left_pan: [-0.4, 0.05, 0], right_pan: [0.4, 0.05, 0] },
  },
  {
    id: 'bar',
    category: 'measure',
    keywords: ['bar', 'amount', 'height', 'level', 'quantity', 'chart', 'measure'],
    dimensions: BOTH,
    colorToken: 'measure.bar',
    render3D: Bar,
    render2D: R2.Bar2D,
    anchors: BOX_ANCHORS,
  },
  {
    id: 'counter_dots',
    category: 'measure',
    keywords: ['count', 'number', 'dots', 'many', 'few', 'several', 'dozen'],
    dimensions: BOTH,
    colorToken: 'ui.accent',
    render3D: CounterDots,
    render2D: R2.CounterDots2D,
    anchors: BOX_ANCHORS,
  },
  // Fallback
  {
    id: 'labeled_card',
    category: 'generic',
    keywords: ['card', 'label', 'note', 'thing', 'concept'],
    dimensions: BOTH,
    colorToken: 'ui.card',
    render3D: LabeledCard,
    render2D: R2.LabeledCard2D,
    anchors: BOX_ANCHORS,
  },
];

/** Registry keyed by primitive id (completeness against the schema enum is unit-tested). */
export const PRIMITIVE_REGISTRY = Object.fromEntries(
  PRIMITIVES.map((def) => [def.id, def]),
) as Record<PrimitiveId, PrimitiveDef>;

/** The primitive that always renders. */
export const FALLBACK_PRIMITIVE_ID: PrimitiveId = 'labeled_card';

/** Looks up a primitive; unknown ids resolve to `labeled_card` so rendering never fails. */
export function getPrimitive(id: string): PrimitiveDef {
  return (
    (PRIMITIVE_REGISTRY as Record<string, PrimitiveDef | undefined>)[id] ??
    PRIMITIVE_REGISTRY.labeled_card
  );
}
