import type { EntityKind } from '@opsis/schema';

/** Words dropped from the front of a noun phrase; quantifiers are kept as an attribute. */
export const DETERMINERS = new Set([
  'a',
  'an',
  'the',
  'this',
  'that',
  'these',
  'those',
  'my',
  'your',
  'our',
  'their',
  'his',
  'her',
  'its',
]);
export const QUANTIFIERS = new Set([
  'some',
  'all',
  'many',
  'most',
  'every',
  'each',
  'few',
  'several',
]);
export const NUMBER_WORDS: Record<string, number> = {
  one: 1,
  two: 2,
  three: 3,
  four: 4,
  five: 5,
  six: 6,
  seven: 7,
  eight: 8,
  nine: 9,
  ten: 10,
};
export const PRONOUNS = new Set(['it', 'them', 'this', 'that', 'they']);

export const DIRECTIONS = [
  'north',
  'south',
  'east',
  'west',
  'northeast',
  'northwest',
  'southeast',
  'southwest',
  'north-east',
  'north-west',
  'south-east',
  'south-west',
  'up',
  'down',
  'left',
  'right',
];

/** Verbs of motion: "X cannot fly" becomes a `moves` relation rather than `agent_of`. */
export const MOTION_VERBS = new Set([
  'fly',
  'swim',
  'run',
  'walk',
  'move',
  'crawl',
  'jump',
  'rise',
  'set',
  'fall',
  'flow',
  'travel',
  'go',
  'orbit',
  'spin',
  'rotate',
  'roll',
  'climb',
  'sink',
  'float',
  'drift',
  'migrate',
  'hop',
  'slide',
  'circle',
  'revolve',
]);

/** Transitive verbs the offline parser trusts in "X verbs Y" sentences. */
export const ACTION_VERBS = new Set([
  ...MOTION_VERBS,
  'pump',
  'eat',
  'drink',
  'make',
  'use',
  'carry',
  'push',
  'pull',
  'heat',
  'cool',
  'produce',
  'absorb',
  'release',
  'build',
  'catch',
  'chase',
  'hold',
  'need',
  'give',
  'send',
  'boil',
  'add',
  'drain',
  'cut',
  'mix',
  'pour',
  'bake',
  'cook',
  'fry',
  'stir',
  'wash',
  'plant',
  'water',
  'grow',
  'digest',
  'breathe',
  'protect',
  'cover',
  'feed',
  'lay',
  'melt',
  'freeze',
]);

/** Change-of-state verbs that may form an offline step chain ("evaporates, forms clouds…"). */
export const STATE_CHANGE_VERBS = new Set([
  'evaporate',
  'condense',
  'form',
  'fall',
  'freeze',
  'melt',
  'boil',
  'cool',
  'collect',
  'precipitate',
  'dissolve',
]);

const IRREGULAR_NOUNS: Record<string, string> = {
  mice: 'mouse',
  geese: 'goose',
  children: 'child',
  people: 'person',
  men: 'man',
  women: 'woman',
  teeth: 'tooth',
  feet: 'foot',
  leaves: 'leaf',
  knives: 'knife',
  loaves: 'loaf',
  wolves: 'wolf',
  halves: 'half',
  lives: 'life',
  oxen: 'ox',
  fungi: 'fungus',
  cacti: 'cactus',
  data: 'data',
};
const IRREGULAR_VERBS: Record<string, string> = {
  is: 'be',
  are: 'be',
  was: 'be',
  were: 'be',
  has: 'have',
  does: 'do',
  goes: 'go',
  flies: 'fly',
  made: 'make',
  ran: 'run',
  rose: 'rise',
  fell: 'fall',
  flew: 'fly',
  ate: 'eat',
  grew: 'grow',
  gave: 'give',
  froze: 'freeze',
  caught: 'catch',
  swam: 'swim',
  went: 'go',
};
const UNCHANGED_NOUNS = new Set([
  'fish',
  'sheep',
  'deer',
  'glass',
  'gas',
  'grass',
  'species',
  'news',
]);

/** Returns the singular dictionary form of one English noun (best effort, no dictionary). */
export function nounLemma(word: string): string {
  const lower = word.toLowerCase();
  if (IRREGULAR_NOUNS[lower]) return IRREGULAR_NOUNS[lower];
  if (UNCHANGED_NOUNS.has(lower) || lower.length <= 3) return lower;
  if (/ies$/u.test(lower)) return `${lower.slice(0, -3)}y`;
  if (/(ss|sh|ch|x|z)es$/u.test(lower)) return lower.slice(0, -2);
  if (/oes$/u.test(lower)) return lower.slice(0, -2);
  if (/[^su]s$/u.test(lower) && !/is$/u.test(lower)) return lower.slice(0, -1);
  return lower;
}

/** Returns the base form of one English verb (best effort, no dictionary). */
export function verbLemma(word: string): string {
  const lower = word.toLowerCase();
  if (IRREGULAR_VERBS[lower]) return IRREGULAR_VERBS[lower];
  if (/[^aeiou]ies$/u.test(lower)) return `${lower.slice(0, -3)}y`;
  if (/(ss|sh|ch|x|z|o)es$/u.test(lower)) return lower.slice(0, -2);
  if (/[^s]s$/u.test(lower)) return lower.slice(0, -1);
  return lower;
}

/** Entity kinds for common lemmas; anything else defaults to `object` (or `place` for names). */
export const KIND_BY_LEMMA: Record<string, EntityKind> = {
  sun: 'celestial_body',
  moon: 'celestial_body',
  earth: 'celestial_body',
  star: 'celestial_body',
  planet: 'celestial_body',
  mars: 'celestial_body',
  jupiter: 'celestial_body',
  comet: 'celestial_body',
  water: 'substance',
  air: 'substance',
  oxygen: 'substance',
  'carbon dioxide': 'substance',
  blood: 'substance',
  sugar: 'substance',
  salt: 'substance',
  ice: 'substance',
  steam: 'substance',
  bread: 'substance',
  ham: 'substance',
  tomato: 'substance',
  cheese: 'substance',
  lettuce: 'substance',
  pasta: 'substance',
  rain: 'substance',
  cloud: 'substance',
  warm: 'abstract_concept',
  cold: 'abstract_concept',
  hot: 'abstract_concept',
  sunlight: 'substance',
  cat: 'living_thing',
  dog: 'living_thing',
  bird: 'living_thing',
  mammal: 'living_thing',
  animal: 'living_thing',
  plant: 'living_thing',
  tree: 'living_thing',
  elephant: 'living_thing',
  mouse: 'living_thing',
  fish: 'living_thing',
  insect: 'living_thing',
  whale: 'living_thing',
  bat: 'living_thing',
  spider: 'living_thing',
  penguin: 'living_thing',
  reptile: 'living_thing',
  heart: 'object',
  lung: 'object',
  sandwich: 'object',
  atom: 'object',
  nucleus: 'object',
  electron: 'object',
  bicycle: 'object',
  wheel: 'object',
  person: 'person',
  you: 'person',
  child: 'person',
  teacher: 'person',
  heat: 'process',
  rotation: 'process',
  evaporation: 'process',
};

/** Short, factual summaries (≤ 25 words) the offline parser can state with confidence. */
export const SUMMARY_BY_LEMMA: Record<string, string> = {
  sun: 'The Sun is the star at the centre of our solar system.',
  moon: 'The Moon is the natural satellite that orbits Earth.',
  earth: 'Earth is the planet we live on, the third planet from the Sun.',
  east: 'East is the direction where the Sun appears to rise.',
  west: 'West is the direction where the Sun appears to set.',
  north: 'North is the direction a compass needle points towards.',
  south: 'South is the direction opposite north on a compass.',
  rise: 'To rise is to move upward.',
  sandwich: 'A sandwich layers fillings between pieces of bread.',
  bread: 'Bread is a baked food made from flour and water.',
  tomato: 'A tomato is a juicy red fruit often eaten as a vegetable.',
  ham: 'Ham is a cured meat from a pig’s leg.',
  cat: 'A cat is a small furry mammal often kept as a pet.',
  mammal: 'A mammal is a warm-blooded animal with hair that feeds its young milk.',
  animal: 'An animal is a living thing that eats food and can usually move.',
  elephant: 'An elephant is the largest land animal, with a trunk and tusks.',
  mouse: 'A mouse is a small rodent with a pointed nose and long tail.',
  bird: 'Birds are feathered animals with wings that lay eggs.',
  fly: 'To fly is to move through the air, usually by flapping wings.',
  water: 'Water is a clear liquid that all known living things need.',
  pasta: 'Pasta is a food made from wheat dough, cooked in boiling water.',
  boil: 'To boil is to heat a liquid until it bubbles and turns to vapour.',
  add: 'To add is to put something into something else.',
  drain: 'To drain is to pour away the liquid, keeping the solid food.',
  nairobi: 'Nairobi is the capital city of Kenya.',
  mombasa: 'Mombasa is a coastal city in Kenya on the Indian Ocean.',
  heavy: 'Heavy describes something with a lot of weight.',
  orbit: 'To orbit is to travel around another object in space, held on that path by gravity.',
  ice: 'Ice is water frozen into a solid.',
  melt: 'To melt is to change from a solid into a liquid when warmed.',
  warm: 'Warm means having a fairly high temperature, between cool and hot.',
  cold: 'Cold means having a low temperature.',
  hot: 'Hot means having a high temperature.',
  evaporate: 'To evaporate is to change from a liquid into an invisible gas called vapour.',
  cloud: 'A cloud is a mass of tiny water droplets or ice crystals floating in the air.',
  rain: 'Rain is water that falls from clouds as liquid drops.',
  plant: 'A plant is a living thing that makes its own food using light, water and carbon dioxide.',
  sunlight: 'Sunlight is light from the Sun; plants capture its energy to make food.',
  'carbon dioxide': 'Carbon dioxide is a gas in the air; plants take it in to make sugar.',
  sugar: 'Sugar is a sweet substance; plants make a sugar called glucose to store energy.',
  oxygen: 'Oxygen is a gas in the air that most living things need to breathe.',
  heart: 'The heart is a muscle that pumps blood around the body.',
  pump: 'To pump is to push a liquid or gas along by squeezing or pressing.',
  blood: 'Blood is the red liquid that carries oxygen and food around the body.',
  lung: 'The lungs are two organs in the chest that take oxygen from the air we breathe.',
  atom: 'An atom is the tiny basic unit of matter that all substances are made of.',
  nucleus: 'The nucleus is the tiny, heavy centre of an atom, made of protons and neutrons.',
  electron:
    'An electron is a tiny particle with a negative charge found around the nucleus of an atom.',
  bicycle: 'A bicycle is a two-wheeled vehicle you ride and move by pushing pedals.',
  wheel: 'A wheel is a round part that turns on an axle so something can roll.',
  frame: 'A frame is the rigid structure that holds the other parts together.',
  pedal: 'A pedal is the part you push with your foot to turn a bicycle’s chain.',
  chain: 'A bicycle chain carries the turning force from the pedals to the back wheel.',
};
