import type { LucideIcon } from 'lucide-react';
import {
  Activity,
  Anchor,
  Apple,
  Archive,
  ArrowRightLeft,
  Atom,
  Baby,
  Banknote,
  Battery,
  Bell,
  Bike,
  Binary,
  Bird,
  Blocks,
  Bone,
  BookOpen,
  Bot,
  Box,
  Brain,
  Briefcase,
  Bug,
  Building2,
  Cable,
  Calculator,
  Calendar,
  Camera,
  Car,
  ChartColumn,
  ChartPie,
  Check,
  CircleHelp,
  CircleStop,
  CircleX,
  Clipboard,
  Clock3,
  Cloud,
  CloudLightning,
  CloudRain,
  Code2,
  Coffee,
  Coins,
  Compass,
  Container,
  Cpu,
  CreditCard,
  Database,
  Dna,
  Download,
  Droplet,
  Ear,
  Earth,
  Eye,
  Factory,
  FileText,
  Filter,
  Fingerprint,
  Fish,
  Flag,
  Flame,
  FlaskConical,
  Folder,
  Frown,
  Fuel,
  Gamepad2,
  Gavel,
  GitBranch,
  GitMerge,
  Globe2,
  GraduationCap,
  Hammer,
  Handshake,
  HardDrive,
  Heart,
  HeartPulse,
  Hospital,
  Hourglass,
  House,
  Image,
  Inbox,
  Info,
  KeyRound,
  Landmark,
  Languages,
  Laptop,
  Layers,
  Leaf,
  Lightbulb,
  Link,
  Lock,
  LockOpen,
  Magnet,
  Mail,
  Map,
  MapPin,
  Megaphone,
  MessageCircle,
  MessagesSquare,
  Microscope,
  Monitor,
  Moon,
  Mountain,
  Music,
  Network,
  Newspaper,
  Orbit,
  Package,
  Palette,
  PawPrint,
  PenTool,
  Phone,
  Pill,
  Plane,
  Play,
  Plug,
  Power,
  Puzzle,
  Radio,
  Receipt,
  Recycle,
  RefreshCw,
  Repeat2,
  Rocket,
  Route,
  Router,
  Satellite,
  Scale,
  ScanFace,
  School,
  Search,
  Send,
  Server,
  Settings2,
  Share2,
  ShieldAlert,
  ShieldCheck,
  Ship,
  ShoppingCart,
  Siren,
  Smartphone,
  Smile,
  Snowflake,
  SolarPanel,
  Sprout,
  Star,
  Stethoscope,
  Store,
  Sun,
  Syringe,
  Table,
  Tag,
  Target,
  Telescope,
  Terminal,
  Thermometer,
  ThumbsUp,
  Timer,
  TrainFront,
  TreePine,
  TriangleAlert,
  Trophy,
  Truck,
  Upload,
  UserCheck,
  UserRound,
  Users,
  Utensils,
  Video,
  Vote,
  Wallet,
  Warehouse,
  Waves,
  Webhook,
  Wheat,
  Wifi,
  Wind,
  Workflow,
  Wrench,
  Zap,
} from 'lucide-react';
import type { BoardIcon } from '@opsis/schema';

export type IconEntry = {
  icon: LucideIcon;
  label: string;
  category: IconCategory;
  keywords: string;
};
export const ICON_CATEGORIES = [
  'People',
  'Communication',
  'Computing',
  'Security',
  'Data',
  'Flow',
  'Science',
  'Health',
  'Business',
  'Places',
  'Energy',
  'Everyday',
] as const;
export type IconCategory = (typeof ICON_CATEGORIES)[number];

/** Every schema icon with a readable name, a category and search terms (compile-checked). */
export const ICON_CATALOG: Record<BoardIcon, IconEntry> = {
  user: {
    icon: UserRound,
    label: 'Person',
    category: 'People',
    keywords: 'user human actor client customer individual',
  },
  users: {
    icon: Users,
    label: 'Group',
    category: 'People',
    keywords: 'team people audience crowd community',
  },
  'verified-user': {
    icon: UserCheck,
    label: 'Verified person',
    category: 'People',
    keywords: 'approved authenticated member',
  },
  student: {
    icon: GraduationCap,
    label: 'Student',
    category: 'People',
    keywords: 'learner graduate school university',
  },
  worker: {
    icon: Briefcase,
    label: 'Worker',
    category: 'People',
    keywords: 'employee job business office professional',
  },
  doctor: {
    icon: Stethoscope,
    label: 'Doctor',
    category: 'People',
    keywords: 'clinician nurse medical practitioner',
  },
  baby: { icon: Baby, label: 'Baby', category: 'People', keywords: 'child infant young' },
  hand: {
    icon: Handshake,
    label: 'Agreement',
    category: 'People',
    keywords: 'deal partnership trust contract',
  },
  mail: { icon: Mail, label: 'Email', category: 'Communication', keywords: 'letter message email' },
  send: {
    icon: Send,
    label: 'Send',
    category: 'Communication',
    keywords: 'submit dispatch transmit',
  },
  inbox: { icon: Inbox, label: 'Inbox', category: 'Communication', keywords: 'receive mailbox' },
  message: {
    icon: MessageCircle,
    label: 'Message',
    category: 'Communication',
    keywords: 'chat conversation reply',
  },
  chat: {
    icon: MessagesSquare,
    label: 'Discussion',
    category: 'Communication',
    keywords: 'conversation forum thread',
  },
  phone: { icon: Phone, label: 'Phone', category: 'Communication', keywords: 'call telephone' },
  bell: {
    icon: Bell,
    label: 'Notification',
    category: 'Communication',
    keywords: 'alert notify reminder',
  },
  megaphone: {
    icon: Megaphone,
    label: 'Announcement',
    category: 'Communication',
    keywords: 'broadcast marketing publish',
  },
  video: {
    icon: Video,
    label: 'Video call',
    category: 'Communication',
    keywords: 'camera meeting stream',
  },
  radio: {
    icon: Radio,
    label: 'Radio',
    category: 'Communication',
    keywords: 'broadcast signal wireless',
  },
  news: {
    icon: Newspaper,
    label: 'News',
    category: 'Communication',
    keywords: 'article press media',
  },
  language: {
    icon: Languages,
    label: 'Language',
    category: 'Communication',
    keywords: 'translate words speech',
  },
  server: {
    icon: Server,
    label: 'Server',
    category: 'Computing',
    keywords: 'backend host machine',
  },
  database: {
    icon: Database,
    label: 'Database',
    category: 'Computing',
    keywords: 'storage data records sql',
  },
  cloud: {
    icon: Cloud,
    label: 'Cloud',
    category: 'Computing',
    keywords: 'hosting online internet service',
  },
  cpu: { icon: Cpu, label: 'Processor', category: 'Computing', keywords: 'chip compute hardware' },
  network: {
    icon: Network,
    label: 'Network',
    category: 'Computing',
    keywords: 'nodes topology connections',
  },
  code: {
    icon: Code2,
    label: 'Code',
    category: 'Computing',
    keywords: 'program software source developer',
  },
  terminal: {
    icon: Terminal,
    label: 'Terminal',
    category: 'Computing',
    keywords: 'command line shell console',
  },
  monitor: {
    icon: Monitor,
    label: 'Screen',
    category: 'Computing',
    keywords: 'desktop display computer',
  },
  laptop: { icon: Laptop, label: 'Laptop', category: 'Computing', keywords: 'computer device' },
  'phone-device': {
    icon: Smartphone,
    label: 'Mobile',
    category: 'Computing',
    keywords: 'smartphone app device',
  },
  wifi: {
    icon: Wifi,
    label: 'Wi-Fi',
    category: 'Computing',
    keywords: 'wireless internet connection',
  },
  router: {
    icon: Router,
    label: 'Router',
    category: 'Computing',
    keywords: 'gateway network device',
  },
  storage: {
    icon: HardDrive,
    label: 'Disk',
    category: 'Computing',
    keywords: 'drive storage hardware',
  },
  link: { icon: Link, label: 'Link', category: 'Computing', keywords: 'url hyperlink connect' },
  api: {
    icon: Webhook,
    label: 'API',
    category: 'Computing',
    keywords: 'webhook integration endpoint',
  },
  bot: {
    icon: Bot,
    label: 'Bot',
    category: 'Computing',
    keywords: 'ai agent robot assistant model',
  },
  binary: { icon: Binary, label: 'Binary', category: 'Computing', keywords: 'bits data encoding' },
  merge: { icon: GitMerge, label: 'Merge', category: 'Computing', keywords: 'git branch combine' },
  blocks: {
    icon: Blocks,
    label: 'Modules',
    category: 'Computing',
    keywords: 'components architecture parts',
  },
  globe: {
    icon: Globe2,
    label: 'Internet',
    category: 'Computing',
    keywords: 'web world global dns',
  },
  satellite: {
    icon: Satellite,
    label: 'Satellite',
    category: 'Computing',
    keywords: 'orbit signal space gps',
  },
  shield: {
    icon: ShieldCheck,
    label: 'Protected',
    category: 'Security',
    keywords: 'safe security verified',
  },
  'shield-alert': {
    icon: ShieldAlert,
    label: 'Threat',
    category: 'Security',
    keywords: 'attack danger risk warning',
  },
  key: {
    icon: KeyRound,
    label: 'Key',
    category: 'Security',
    keywords: 'password credential access secret',
  },
  lock: { icon: Lock, label: 'Locked', category: 'Security', keywords: 'secure private encrypted' },
  unlock: {
    icon: LockOpen,
    label: 'Unlocked',
    category: 'Security',
    keywords: 'open access decrypted',
  },
  fingerprint: {
    icon: Fingerprint,
    label: 'Identity',
    category: 'Security',
    keywords: 'biometric login authentication',
  },
  'face-scan': {
    icon: ScanFace,
    label: 'Face scan',
    category: 'Security',
    keywords: 'recognition biometric camera',
  },
  eye: { icon: Eye, label: 'View', category: 'Security', keywords: 'see watch visible observe' },
  bug: { icon: Bug, label: 'Bug', category: 'Security', keywords: 'defect error insect virus' },
  siren: {
    icon: Siren,
    label: 'Emergency',
    category: 'Security',
    keywords: 'alarm incident urgent',
  },
  file: { icon: FileText, label: 'Document', category: 'Data', keywords: 'file text page report' },
  folder: {
    icon: Folder,
    label: 'Folder',
    category: 'Data',
    keywords: 'directory files collection',
  },
  book: { icon: BookOpen, label: 'Book', category: 'Data', keywords: 'read learn knowledge guide' },
  chart: {
    icon: ChartColumn,
    label: 'Bar chart',
    category: 'Data',
    keywords: 'statistics analytics graph metrics',
  },
  pie: {
    icon: ChartPie,
    label: 'Pie chart',
    category: 'Data',
    keywords: 'share proportion percentage',
  },
  table: {
    icon: Table,
    label: 'Table',
    category: 'Data',
    keywords: 'spreadsheet rows columns grid',
  },
  clipboard: { icon: Clipboard, label: 'Checklist', category: 'Data', keywords: 'task form list' },
  archive: { icon: Archive, label: 'Archive', category: 'Data', keywords: 'backup store history' },
  filter: {
    icon: Filter,
    label: 'Filter',
    category: 'Data',
    keywords: 'sort select narrow funnel',
  },
  calculator: {
    icon: Calculator,
    label: 'Calculate',
    category: 'Data',
    keywords: 'math compute numbers',
  },
  tag: { icon: Tag, label: 'Label', category: 'Data', keywords: 'category tag price' },
  split: {
    icon: GitBranch,
    label: 'Branch',
    category: 'Flow',
    keywords: 'fork decision split path',
  },
  repeat: { icon: Repeat2, label: 'Repeat', category: 'Flow', keywords: 'loop cycle retry' },
  refresh: {
    icon: RefreshCw,
    label: 'Update',
    category: 'Flow',
    keywords: 'refresh sync reload renew',
  },
  workflow: {
    icon: Workflow,
    label: 'Workflow',
    category: 'Flow',
    keywords: 'process pipeline steps',
  },
  exchange: {
    icon: ArrowRightLeft,
    label: 'Exchange',
    category: 'Flow',
    keywords: 'swap transfer two-way trade',
  },
  check: { icon: Check, label: 'Done', category: 'Flow', keywords: 'complete success ok yes' },
  cross: { icon: CircleX, label: 'Rejected', category: 'Flow', keywords: 'fail no cancel error' },
  alert: {
    icon: TriangleAlert,
    label: 'Warning',
    category: 'Flow',
    keywords: 'error caution problem',
  },
  help: { icon: CircleHelp, label: 'Question', category: 'Flow', keywords: 'unknown help ask' },
  info: { icon: Info, label: 'Information', category: 'Flow', keywords: 'note detail about' },
  clock: { icon: Clock3, label: 'Time', category: 'Flow', keywords: 'wait schedule time' },
  timer: { icon: Timer, label: 'Timer', category: 'Flow', keywords: 'timeout countdown duration' },
  hourglass: {
    icon: Hourglass,
    label: 'Waiting',
    category: 'Flow',
    keywords: 'delay pending queue',
  },
  calendar: { icon: Calendar, label: 'Date', category: 'Flow', keywords: 'schedule plan event' },
  play: { icon: Play, label: 'Start', category: 'Flow', keywords: 'begin run trigger' },
  stop: { icon: CircleStop, label: 'Stop', category: 'Flow', keywords: 'end halt finish' },
  flag: { icon: Flag, label: 'Milestone', category: 'Flow', keywords: 'goal finish marker' },
  target: { icon: Target, label: 'Goal', category: 'Flow', keywords: 'aim objective outcome' },
  puzzle: {
    icon: Puzzle,
    label: 'Piece',
    category: 'Flow',
    keywords: 'part component fit problem',
  },
  zap: { icon: Zap, label: 'Event', category: 'Flow', keywords: 'trigger energy fast power' },
  settings: {
    icon: Settings2,
    label: 'Settings',
    category: 'Flow',
    keywords: 'configure options control',
  },
  search: { icon: Search, label: 'Search', category: 'Flow', keywords: 'find lookup query' },
  lightbulb: {
    icon: Lightbulb,
    label: 'Idea',
    category: 'Flow',
    keywords: 'insight concept thought',
  },
  layers: { icon: Layers, label: 'Layers', category: 'Flow', keywords: 'stack levels tiers' },
  box: { icon: Box, label: 'Box', category: 'Flow', keywords: 'package container item thing' },
  share: { icon: Share2, label: 'Share', category: 'Flow', keywords: 'distribute publish spread' },
  download: { icon: Download, label: 'Download', category: 'Flow', keywords: 'fetch get receive' },
  upload: { icon: Upload, label: 'Upload', category: 'Flow', keywords: 'push put transmit' },
  atom: {
    icon: Atom,
    label: 'Atom',
    category: 'Science',
    keywords: 'physics particle chemistry nucleus',
  },
  flask: {
    icon: FlaskConical,
    label: 'Experiment',
    category: 'Science',
    keywords: 'chemistry lab reaction',
  },
  microscope: {
    icon: Microscope,
    label: 'Microscope',
    category: 'Science',
    keywords: 'biology cell research',
  },
  dna: { icon: Dna, label: 'DNA', category: 'Science', keywords: 'gene genetics biology heredity' },
  magnet: {
    icon: Magnet,
    label: 'Magnet',
    category: 'Science',
    keywords: 'force attraction physics',
  },
  orbit: {
    icon: Orbit,
    label: 'Orbit',
    category: 'Science',
    keywords: 'planet space gravity solar',
  },
  earth: { icon: Earth, label: 'Earth', category: 'Science', keywords: 'planet world geography' },
  telescope: {
    icon: Telescope,
    label: 'Telescope',
    category: 'Science',
    keywords: 'astronomy space observe',
  },
  rocket: { icon: Rocket, label: 'Rocket', category: 'Science', keywords: 'launch space fast' },
  thermometer: {
    icon: Thermometer,
    label: 'Temperature',
    category: 'Science',
    keywords: 'heat cold measure',
  },
  sun: { icon: Sun, label: 'Sun', category: 'Science', keywords: 'light energy day solar' },
  moon: { icon: Moon, label: 'Moon', category: 'Science', keywords: 'night lunar' },
  rain: {
    icon: CloudRain,
    label: 'Rain',
    category: 'Science',
    keywords: 'weather precipitation water cycle',
  },
  storm: {
    icon: CloudLightning,
    label: 'Storm',
    category: 'Science',
    keywords: 'weather lightning thunder',
  },
  wind: { icon: Wind, label: 'Wind', category: 'Science', keywords: 'air weather breeze' },
  droplet: {
    icon: Droplet,
    label: 'Water',
    category: 'Science',
    keywords: 'liquid drop water cycle',
  },
  flame: { icon: Flame, label: 'Fire', category: 'Science', keywords: 'heat burn combustion' },
  snowflake: { icon: Snowflake, label: 'Ice', category: 'Science', keywords: 'cold freeze snow' },
  waves: { icon: Waves, label: 'Waves', category: 'Science', keywords: 'ocean sea sound signal' },
  mountain: {
    icon: Mountain,
    label: 'Mountain',
    category: 'Science',
    keywords: 'land terrain geology',
  },
  leaf: { icon: Leaf, label: 'Leaf', category: 'Science', keywords: 'plant nature photosynthesis' },
  tree: { icon: TreePine, label: 'Tree', category: 'Science', keywords: 'forest plant nature' },
  sprout: { icon: Sprout, label: 'Growth', category: 'Science', keywords: 'seed plant grow' },
  fish: { icon: Fish, label: 'Fish', category: 'Science', keywords: 'animal ocean' },
  bird: { icon: Bird, label: 'Bird', category: 'Science', keywords: 'animal flight' },
  animal: { icon: PawPrint, label: 'Animal', category: 'Science', keywords: 'pet mammal wildlife' },
  recycle: {
    icon: Recycle,
    label: 'Recycle',
    category: 'Science',
    keywords: 'reuse sustainability cycle',
  },
  heart: { icon: Heart, label: 'Heart', category: 'Health', keywords: 'love care health' },
  pulse: {
    icon: HeartPulse,
    label: 'Heartbeat',
    category: 'Health',
    keywords: 'vital health cardio',
  },
  activity: {
    icon: Activity,
    label: 'Activity',
    category: 'Health',
    keywords: 'signal monitor vitals',
  },
  brain: { icon: Brain, label: 'Brain', category: 'Health', keywords: 'mind think neuroscience' },
  pill: { icon: Pill, label: 'Medicine', category: 'Health', keywords: 'drug treatment pharmacy' },
  syringe: { icon: Syringe, label: 'Vaccine', category: 'Health', keywords: 'injection dose' },
  hospital: { icon: Hospital, label: 'Hospital', category: 'Health', keywords: 'clinic care' },
  bone: { icon: Bone, label: 'Bone', category: 'Health', keywords: 'skeleton body' },
  ear: { icon: Ear, label: 'Hearing', category: 'Health', keywords: 'listen sound' },
  cart: {
    icon: ShoppingCart,
    label: 'Cart',
    category: 'Business',
    keywords: 'shop buy purchase order',
  },
  store: { icon: Store, label: 'Shop', category: 'Business', keywords: 'retail merchant market' },
  wallet: { icon: Wallet, label: 'Wallet', category: 'Business', keywords: 'money pay funds' },
  card: { icon: CreditCard, label: 'Payment', category: 'Business', keywords: 'card pay checkout' },
  coins: { icon: Coins, label: 'Coins', category: 'Business', keywords: 'money cash currency' },
  banknote: { icon: Banknote, label: 'Cash', category: 'Business', keywords: 'money price cost' },
  receipt: {
    icon: Receipt,
    label: 'Receipt',
    category: 'Business',
    keywords: 'invoice bill order',
  },
  bank: {
    icon: Landmark,
    label: 'Bank',
    category: 'Business',
    keywords: 'government institution finance',
  },
  scale: {
    icon: Scale,
    label: 'Law',
    category: 'Business',
    keywords: 'justice balance legal compare',
  },
  gavel: { icon: Gavel, label: 'Ruling', category: 'Business', keywords: 'court judge decision' },
  vote: { icon: Vote, label: 'Vote', category: 'Business', keywords: 'election ballot choose' },
  trophy: { icon: Trophy, label: 'Award', category: 'Business', keywords: 'win prize achievement' },
  star: {
    icon: Star,
    label: 'Favourite',
    category: 'Business',
    keywords: 'rating quality highlight',
  },
  'thumbs-up': {
    icon: ThumbsUp,
    label: 'Approve',
    category: 'Business',
    keywords: 'like feedback agree',
  },
  home: { icon: House, label: 'Home', category: 'Places', keywords: 'house residence' },
  building: {
    icon: Building2,
    label: 'Building',
    category: 'Places',
    keywords: 'office company organisation',
  },
  factory: {
    icon: Factory,
    label: 'Factory',
    category: 'Places',
    keywords: 'manufacturing industry production',
  },
  warehouse: {
    icon: Warehouse,
    label: 'Warehouse',
    category: 'Places',
    keywords: 'storage inventory logistics',
  },
  school: { icon: School, label: 'School', category: 'Places', keywords: 'education learning' },
  map: { icon: Map, label: 'Map', category: 'Places', keywords: 'geography route plan' },
  pin: {
    icon: MapPin,
    label: 'Location',
    category: 'Places',
    keywords: 'place address destination',
  },
  route: { icon: Route, label: 'Route', category: 'Places', keywords: 'path journey directions' },
  compass: {
    icon: Compass,
    label: 'Direction',
    category: 'Places',
    keywords: 'navigate orientation north',
  },
  package: {
    icon: Package,
    label: 'Parcel',
    category: 'Places',
    keywords: 'delivery shipment order',
  },
  truck: {
    icon: Truck,
    label: 'Truck',
    category: 'Places',
    keywords: 'delivery logistics transport',
  },
  car: { icon: Car, label: 'Car', category: 'Places', keywords: 'vehicle drive road' },
  train: { icon: TrainFront, label: 'Train', category: 'Places', keywords: 'rail transport' },
  plane: { icon: Plane, label: 'Plane', category: 'Places', keywords: 'flight travel airport' },
  ship: { icon: Ship, label: 'Ship', category: 'Places', keywords: 'boat sea freight' },
  anchor: { icon: Anchor, label: 'Port', category: 'Places', keywords: 'harbour dock ship' },
  bike: { icon: Bike, label: 'Bicycle', category: 'Places', keywords: 'cycle travel' },
  container: {
    icon: Container,
    label: 'Container',
    category: 'Places',
    keywords: 'shipping cargo freight',
  },
  power: { icon: Power, label: 'Power', category: 'Energy', keywords: 'on off switch' },
  plug: { icon: Plug, label: 'Plug', category: 'Energy', keywords: 'electricity connect socket' },
  battery: { icon: Battery, label: 'Battery', category: 'Energy', keywords: 'charge store energy' },
  solar: { icon: SolarPanel, label: 'Solar', category: 'Energy', keywords: 'renewable panel sun' },
  fuel: { icon: Fuel, label: 'Fuel', category: 'Energy', keywords: 'petrol gas oil' },
  hammer: { icon: Hammer, label: 'Build', category: 'Energy', keywords: 'make construct tool' },
  wrench: { icon: Wrench, label: 'Fix', category: 'Energy', keywords: 'repair maintain tool' },
  cable: { icon: Cable, label: 'Cable', category: 'Energy', keywords: 'wire connection' },
  food: { icon: Utensils, label: 'Food', category: 'Everyday', keywords: 'meal eat restaurant' },
  coffee: { icon: Coffee, label: 'Drink', category: 'Everyday', keywords: 'cafe break' },
  apple: { icon: Apple, label: 'Fruit', category: 'Everyday', keywords: 'food health nutrition' },
  wheat: { icon: Wheat, label: 'Crop', category: 'Everyday', keywords: 'farm grain agriculture' },
  camera: { icon: Camera, label: 'Photo', category: 'Everyday', keywords: 'picture capture' },
  image: { icon: Image, label: 'Image', category: 'Everyday', keywords: 'picture media' },
  music: { icon: Music, label: 'Music', category: 'Everyday', keywords: 'sound song audio' },
  game: { icon: Gamepad2, label: 'Game', category: 'Everyday', keywords: 'play fun' },
  palette: {
    icon: Palette,
    label: 'Design',
    category: 'Everyday',
    keywords: 'art colour creative',
  },
  pen: { icon: PenTool, label: 'Draw', category: 'Everyday', keywords: 'write design edit' },
  smile: { icon: Smile, label: 'Happy', category: 'Everyday', keywords: 'positive emotion' },
  frown: { icon: Frown, label: 'Unhappy', category: 'Everyday', keywords: 'negative emotion' },
};

export const boardIcons = Object.fromEntries(
  Object.entries(ICON_CATALOG).map(([name, entry]) => [name, entry.icon]),
) as Record<BoardIcon, LucideIcon>;

/** Match by name, label or keyword; every word of the query must match something. */
export function searchIcons(query: string, category: IconCategory | 'All' = 'All'): BoardIcon[] {
  const words = query.toLowerCase().split(/\s+/).filter(Boolean);
  return (Object.keys(ICON_CATALOG) as BoardIcon[]).filter((name) => {
    const entry = ICON_CATALOG[name];
    if (category !== 'All' && entry.category !== category) return false;
    const haystack = `${name} ${entry.label} ${entry.keywords}`.toLowerCase();
    return words.every((word) => haystack.includes(word));
  });
}
